### ISSUE TITLE
[CLOSED] Error Using Java 8 And Spigot 1.8.8.

### ISSUE THREAD

**Issue by TheIntelloBox** [sainttx/Auction#12]
[13:30:37] [Server thread/WARN]: [Auctions] Task #99645 for Auctions v2.5.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
    at com.sainttx.auctions.util.AuctionUtil.getFreeSlots(AuctionUtil.java:48) ~[?:?]
    at com.sainttx.auctions.api.reward.ItemReward.giveItem(ItemReward.java:68) ~[?:?]
    at com.sainttx.auctions.structure.DefaultAuction.end(DefaultAuction.java:185) ~[?:?]
    at com.sainttx.auctions.structure.AbstractAuction$AuctionTimer.run(AbstractAuction.java:215) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

And http://hastebin.com/zoyegosile.bash

**Comment by TheIntelloBox** [comment]
Closed. x)
