### ISSUE TITLE
Minecraft 1.12

### ISSUE THREAD

**Issue by ghost** [sainttx/Auction#17]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?e530ec22a9a314e7#BxkLp2bBEOqJ90NlC4NT8mhxo0CWo+SlHTCwjG1rT9g=

Just giving you a heads up before 1.12 is released

**Comment by LunaSquee** [comment]
Your patch might help but it still doesn't build for me

**Comment by TuxCoding** [comment]
@LunaSquee What error do you got?

**Comment by Sheemap** [comment]
Still not workin

Heres the error it throws

```
[08:47:34 ERROR]: Error occurred while enabling Auctions v2.5.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.sainttx.auctions.AuctionPlugin.checkOutdatedConfig(AuctionPlugin.java:175) ~[?:?]
        at com.sainttx.auctions.AuctionPlugin.onEnable(AuctionPlugin.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:748) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) [spigot.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630) [spigot.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-14b597f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
